import { convexTest } from "convex-test";
import { expect, test } from "vitest";
import schema from "../convex/schema";
import { api, internal } from "../convex/_generated/api";
import { compare, validateDetails, type Details } from "../convex/offerFields";
import { checkExtraction } from "../convex/ai";
const modules=import.meta.glob("../convex/**/*.*s");
const details:Details={brand:"Example brand",model:"C60",specifications:"60 cm",inclusions:"Product only",warranty:"1 year",installation:"60 cm space",service:"Needs checking",availability:"Shop says in stock",quoteDate:"2026-10-01",validUntil:"Not provided",price:22000,installationCost:null,deliveryCost:500,otherCost:null,fit:"unknown",fitReasons:""};
test("unknown costs never become zero; incomplete or expired evidence blocks fit",()=>{
 expect(compare(25000,[{slot:1,details}])[0]).toMatchObject({total:null,fit:"Fit needs checking",finalRecommendationBlocked:true});
 const complete={...details,installationCost:0,otherCost:0,service:"Local service phone recorded",validUntil:"2099-01-01",fit:"yes" as const,fitReasons:"60 cm fits the measured space"};
 expect(compare(25000,[{slot:1,details:complete}])[0]).toMatchObject({total:22500,fit:"Fits your stated needs"});
 expect(compare(0.3,[{slot:1,details:{...complete,price:0.1,deliveryCost:0.2}}])[0]).toMatchObject({total:0.3,fit:"Fits your stated needs"});
 expect(compare(20000,[{slot:1,details:complete}])[0].fit).toBe("Does not fit your stated needs");
 expect(compare(25000,[{slot:1,details:{...complete,validUntil:"2020-01-01"}}])[0].finalRecommendationBlocked).toBe(true);
 expect(()=>validateDetails({...details,quoteDate:"2026-02-30"})).toThrow();
});
test("two owned offers and comparison persist, retries do not duplicate, corrections preserve originals and make comparison stale",async()=>{
 const t=convexTest(schema,modules);
 const [a,b]=await t.run(async ctx=>Promise.all([ctx.db.insert("users",{email:"offers-a@example.test"}),ctx.db.insert("users",{email:"offers-b@example.test"})]));
 const alice=t.withIdentity({subject:`${a}|session`}),bob=t.withIdentity({subject:`${b}|session`});
 await alice.mutation(api.purchases.save,{item:"Chimney",budget:25000,situation:"60 cm space"});
 await bob.mutation(api.purchases.save,{item:"Fridge",budget:30000,situation:"Family"});
 const source=await alice.mutation(api.offers.saveSource,{slot:1,notes:"Original made-up note"});
 expect(await alice.mutation(api.offers.saveSource,{slot:1,notes:"Original made-up note"})).toBe(source);
 await expect(alice.mutation(api.offers.saveSource,{slot:1,notes:"Changed note"})).rejects.toThrow("Original notes");
 await expect(bob.mutation(api.offers.confirm,{slot:1,shop:"Other",captureId:source,details})).rejects.toThrow("not part");
 await expect(bob.query(internal.offers.sourceForAction,{captureId:source})).rejects.toThrow();
 const offer=await alice.mutation(api.offers.confirm,{slot:1,shop:"Example shop A",captureId:source,details});
 expect(await alice.mutation(api.offers.confirm,{slot:1,shop:"Example shop A",captureId:source,details})).toBe(offer);
 await expect(alice.mutation(api.offers.updateComparison,{})).rejects.toThrow("two");
 const second=await alice.mutation(api.offers.saveSource,{slot:2,notes:"Example shop B note"});
 await alice.mutation(api.offers.confirm,{slot:2,shop:"Example shop B",captureId:second,details:{...details,price:26000}});
 await alice.mutation(api.offers.updateComparison,{});
 let result=await alice.query(api.offers.current);expect(result.offers).toHaveLength(2);expect(result.comparison?.stale).toBe(false);expect(result.comparison?.rows[1].fit).toBe("Does not fit your stated needs");
 expect((await bob.query(api.offers.current)).offers).toHaveLength(0);
 await expect(t.query(api.offers.current)).rejects.toThrow("Sign in");
 await alice.mutation(api.purchases.save,{item:"Chimney",budget:21000,situation:"60 cm space"});
 result=await alice.query(api.offers.current);expect(result.comparison?.stale).toBe(true);expect(result.comparison?.budget).toBe(25000);expect(result.comparison?.offers[0].details.price).toBe(22000);expect(result.captures[0].notes).toBe("Original made-up note");
 await alice.mutation(api.offers.confirm,{slot:1,shop:"Example shop A",captureId:source,details:{...details,price:21000}});
 result=await alice.query(api.offers.current);expect(result.comparison?.offers[0].details.price).toBe(22000);expect(result.offers[0].details.price).toBe(21000);
 await expect(alice.mutation(api.offers.saveSource,{slot:3,notes:"No third shop"})).rejects.toThrow("two");
});
test("AI evidence must match original notes and rates are enforced on the backend",async()=>{
 const blank=Object.fromEntries([...Object.keys(details).filter(k=>!['fit','fitReasons'].includes(k))].map(k=>[k,{value:null,source:null,evidence:""}]));
 expect(()=>checkExtraction({...blank,model:{value:"C60",source:0,evidence:"invented"}},"Original note",0)).toThrow();
 expect(()=>checkExtraction({...blank,model:{value:"C60",source:2,evidence:"C60"}},"C60",1)).toThrow();
 expect(checkExtraction({...blank,model:{value:"C60",source:0,evidence:"C60"}},"Model C60",0).model.value).toBe("C60");
 const t=convexTest(schema,modules);const id=await t.run(ctx=>ctx.db.insert("users",{email:"limits@example.test"}));const buyer=t.withIdentity({subject:`${id}|session`});
 await buyer.mutation(api.purchases.save,{item:"Chimney",budget:25000,situation:"Kitchen"});
 for(let n=0;n<10;n++)await buyer.mutation(internal.offers.reserveAI,{});
 await expect(buyer.mutation(internal.offers.reserveAI,{})).rejects.toThrow("Busy");
});
