import React, { useEffect, useState } from "react";
import { useAction, useMutation, useQuery } from "convex/react";
import { api } from "../convex/_generated/api";
const labels={brand:"Brand",model:"Exact model",specifications:"Specifications and units",inclusions:"What the quoted price includes",warranty:"Warranty",installation:"Installation and fit requirements",service:"Local service",availability:"Availability",quoteDate:"Quote date (YYYY-MM-DD)",validUntil:"Valid until (YYYY-MM-DD)",price:"Quoted price (₹)",installationCost:"Extra installation cost (₹)",deliveryCost:"Extra delivery cost (₹)",otherCost:"Other extra costs (₹)"};
const amounts=["price","installationCost","deliveryCost","otherCost"];
const empty=()=>({...Object.fromEntries(Object.keys(labels).map(k=>[k,""])),fit:"unknown",fitReasons:""});
const rupees=n=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(n);
const time=n=>new Date(n).toLocaleString("en-IN");
export const readDraft=key=>{try{return JSON.parse(localStorage.getItem(key)||"null");}catch{return null;}};
function writeDraft(key,value){try{localStorage.setItem(key,JSON.stringify(value));}catch{/* Form stays available if device storage is full. */}}
const message=e=>typeof e.data==="string"?e.data:"Couldn't save. Check your connection and try again; your entries are still here.";
function Sources({capture}){return capture && <details><summary>Original sources</summary>{capture.notes && <pre>{capture.notes}</pre>}{capture.attachments.map(a=><p key={a._id}>{a.url?<a href={a.url} target="_blank" rel="noreferrer">{a.name} — open original photo</a>:"Photo unavailable. Try reopening."}</p>)}</details>;}
async function dataURL(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});}
async function photoCopy(file){let bitmap; try{bitmap=await createImageBitmap(file);}catch{throw {data:"Couldn’t read this photo. Select a different JPEG or PNG and retry."};}try{const scale=Math.min(1,1024/Math.max(bitmap.width,bitmap.height));const canvas=document.createElement("canvas");canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);return canvas.toDataURL("image/jpeg",.9);}finally{bitmap.close();}}
function OfferEditor({slot,purchase,capture,offer,onClose}){
  const key=`offer-draft:${purchase._id}:${slot}`;
  const [draft,setDraft]=useState(()=>readDraft(key)||{shop:offer?.shop||"",notes:capture?.notes|| (slot===1 ? readDraft("first-shop-draft")?.notes||"" : ""),details:offer?Object.fromEntries(Object.entries(offer.details).map(([k,v])=>[k,v===null?"":v])):empty(),evidence:{},review:!!offer});
  const [busy,setBusy]=useState("");const [error,setError]=useState("");const [status,setStatus]=useState("Not saved yet");
  const [file,setFile]=useState(null);const [requestId,setRequestId]=useState("");
  const saveSource=useMutation(api.offers.saveSource);const confirm=useMutation(api.offers.confirm);const upload=useAction(api.ai.uploadPhoto);const read=useAction(api.ai.readSource);
  useEffect(()=>{writeDraft(key,draft);},[key,draft]);
  useEffect(()=>{if(error)document.querySelector(".editor .error")?.focus();},[error]);
  useEffect(()=>{const handler=e=>{if(file || status!=="Saved"){e.preventDefault();e.returnValue="";}};window.addEventListener("beforeunload",handler);return()=>window.removeEventListener("beforeunload",handler);},[file,status]);
  const change=patch=>{setDraft(d=>({...d,...patch}));setStatus("Changes not saved");};
  async function source(){return capture?capture._id:await saveSource({slot,notes:draft.notes});}
  async function prepare(){setBusy("Saving source…");setError("");try{await source();change({review:true});setStatus("Source saved; offer not saved yet");}catch(e){setError(message(e));}finally{setBusy("");}}
  async function uploadFile(){if(!file)return;setBusy("Uploading photo…");setError("");try{if(!["image/jpeg","image/png"].includes(file.type)||file.size>5*1024*1024)throw {data:"Choose a JPEG or PNG photo under 5 MB."};const captureId=await source();await upload({captureId,name:file.name.slice(0,150),original:await dataURL(file),processing:await photoCopy(file),requestId});setFile(null);setStatus("Photo saved; offer not saved yet");}catch(e){setError(message(e));}finally{setBusy("");}}
  async function extract(){setBusy("Reading your sources…");setError("");try{const captureId=await source();const result=await read({captureId});const details=empty();for(const k of Object.keys(labels)) details[k]=result[k]?.value??"";change({details,evidence:result,review:true});setStatus("AI details need your confirmation");}catch(e){setError(message(e));change({review:true});}finally{setBusy("");}}
  async function save(e){e.preventDefault();if(file){setError("Upload the selected photo or remove it before saving.");return;}setBusy("Saving…");setStatus("Saving…");setError("");try{const captureId=await source();const details={...draft.details};for(const k of Object.keys(labels))details[k]=amounts.includes(k)?(details[k]===""?null:Number(details[k])):(details[k].trim()||"Not provided");await confirm({slot,shop:draft.shop,captureId,details});localStorage.removeItem(key);if(slot===1)localStorage.removeItem("first-shop-draft");setStatus("Saved");onClose();}catch(e){setError(message(e));setStatus("Changes not saved");}finally{setBusy("");}}
  return <section className="sheet editor"><button className="text-button" onClick={onClose} disabled={!!busy}>Back to offers</button><h2>{offer?"Correct":"Add"} shop {slot}</h2>
    <p role="status">Save status: {busy||status}{offer && ` · Last saved ${time(offer.confirmedAt)}`}</p><p className="hint">Draft on this device; not saved to your account. Original saved sources stay attached when details change.</p>
    {error && <p className="error" role="alert" tabIndex={-1}>{error} <a href="#shop">Review shop details</a></p>}
    <label htmlFor="shop">Shop name</label><input id="shop" value={draft.shop} maxLength={120} onChange={e=>change({shop:e.target.value})} disabled={!!busy}/>
    {!capture?<><label htmlFor="note">Write or paste your original note</label><textarea id="note" value={draft.notes} maxLength={6000} rows={5} onChange={e=>change({notes:e.target.value})} disabled={!!busy}/><p className="hint">You can leave notes blank when adding a photo. Original notes are kept as evidence after the first source save.</p></>:<Sources capture={capture}/>}
    <label htmlFor="photo">Add photo or screenshot</label><input id="photo" type="file" accept="image/jpeg,image/png" disabled={!!busy || capture?.attachments.length>=2} onChange={e=>{setFile(e.target.files?.[0]||null);setRequestId(Array.from(crypto.getRandomValues(new Uint8Array(16)), b=>b.toString(16).padStart(2,"0")).join(""));setError("");}}/>
    <p className="hint">JPEG or PNG, up to 5 MB; two photos per shop. Unuploaded files need selecting again after reload.</p>
    {file && <div className="actions"><button className="secondary" onClick={uploadFile} disabled={!!busy}>Retry / upload {file.name}</button><button className="text-button" disabled={!!busy} onClick={()=>setFile(null)}>Remove selected photo</button></div>}
    <div className="actions"><button className="secondary" disabled={!!busy||!!file||(!draft.notes.trim()&&!capture?.attachments.length)} onClick={extract}>Read sources with AI</button><button className="primary" disabled={!!busy||!!file||(!draft.notes.trim()&&!capture?.attachments.length)} onClick={prepare}>Enter / review details</button></div>
    <p className="hint">AI sends only these shop sources to OpenAI. Its reading must be checked by you. If reading is unavailable, enter details manually.</p>
    {draft.review && <form onSubmit={save}><h2>Confirm captured details</h2><p>Leave missing amounts blank. Enter 0 only when a cost is explicitly included or free. For unclear text, enter Needs checking.</p>
      {Object.entries(labels).map(([k,label])=><React.Fragment key={k}><label htmlFor={k}>{label}</label>{amounts.includes(k)?<input id={k} type="number" min="0" step="0.01" inputMode="decimal" max="100000000" value={draft.details[k]} onChange={e=>change({details:{...draft.details,[k]:e.target.value}})} disabled={!!busy}/>:<textarea id={k} rows={k==="specifications"||k==="inclusions"?3:2} maxLength={2000} placeholder="Not provided" value={draft.details[k]} onChange={e=>change({details:{...draft.details,[k]:e.target.value}})} disabled={!!busy}/>}{draft.evidence[k]?.value!==null && draft.evidence[k]?.evidence && <p className="hint">Source {draft.evidence[k].source}: “{draft.evidence[k].evidence}” — check against the original.</p>}</React.Fragment>)}
      <label htmlFor="fit">Does this match your stated needs?</label><select id="fit" value={draft.details.fit} onChange={e=>change({details:{...draft.details,fit:e.target.value}})} disabled={!!busy}><option value="unknown">Needs checking</option><option value="yes">Yes, based on my checks</option><option value="no">No</option></select>
      <label htmlFor="fitReasons">Reasons against your needs</label><textarea id="fitReasons" maxLength={2000} value={draft.details.fitReasons} required={draft.details.fit!=="unknown"} onChange={e=>change({details:{...draft.details,fitReasons:e.target.value}})} disabled={!!busy}/>
      <label className="check"><input type="checkbox" required disabled={!!busy}/> I checked these details against my sources; unclear details stay unknown.</label>
      <p>Buyer-confirmed transcription means the capture matches your account. Shopkeeper said; not verified remains true for unsupported claims.</p><button className="primary" disabled={!!busy||!draft.shop.trim()}>{busy||"Confirm and save offer"}</button></form>}
  </section>;
}
export default function Offers({purchase}){
  const data=useQuery(api.offers.current);const update=useMutation(api.offers.updateComparison);const [slot,setSlot]=useState(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  if(!data)return <p role="status">Loading saved offers and comparison…</p>;
  if(slot)return <OfferEditor key={slot} slot={slot} purchase={purchase} capture={data.captures.find(c=>c.slot===slot)} offer={data.offers.find(o=>o.slot===slot)} onClose={()=>setSlot(null)}/>;
  async function compare(){setBusy(true);setError("");try{await update();}catch(e){setError(message(e));}finally{setBusy(false);}}
  const comparison=data.comparison;
  return <section className="offers"><h2>Your shop offers</h2><p>Compare two offers against your needs. Sources are shop statements, not independently verified product facts.</p>
    {[1,2].map(s=>{const o=data.offers.find(o=>o.slot===s);const c=data.captures.find(c=>c.slot===s);return <section className="offer-row" key={s}><h3>{o?o.shop:`Shop ${s}`}</h3>{o?<><p>{o.details.brand} · {o.details.model} · {o.details.price===null?"Price: Not provided":rupees(o.details.price)}</p><p className="hint">Buyer-confirmed transcription · {time(o.confirmedAt)}<br/>Shopkeeper said; not verified<br/>Save status: Saved</p></>:<p>{c?"Original sources saved; offer not confirmed yet.":"No offer saved yet."}</p>}<Sources capture={c}/><button className="secondary" onClick={()=>setSlot(s)}>{o?`Correct shop ${s} details`:c?`Resume shop ${s}`:`Add shop ${s}`}</button></section>;})}
    {error && <p className="error" role="alert">{error}</p>}
    <button className="primary" disabled={busy||data.offers.length<2} onClick={compare}>{busy?"Updating your comparison…":comparison?"Update comparison":"Compare offers"}</button>
    {data.offers.length<2 && <p className="hint">Confirm two offers to save a comparison.</p>}
    {comparison && <section className="comparison"><h2>Your comparison</h2><p role="status">{comparison.stale?"Out of date — needs or offers changed. Update comparison before using it.":busy?"Updating — earlier comparison":"Save status: Saved"} · Last saved {time(comparison.updatedAt)}</p>
      <p>{comparison.stale?"Earlier result — update it before choosing.":comparison.rows.every(r=>r.fit==="Does not fit your stated needs")?"No offer fits your stated needs.":comparison.rows.some(r=>r.finalRecommendationBlocked)?"Check these details before choosing. Critical gaps block a final recommendation.":"Review the reasons and inspect the products before choosing."}</p>
      <p className="hint">Different models and inclusions are not equivalent quotes. Fit reflects your stated checks and budget; it does not verify shop claims.</p>
      <p id="swipe">Swipe sideways to compare offers</p><div className="table-scroll" role="region" aria-labelledby="swipe" tabIndex={0}><table><caption>{comparison.item} · Budget used {rupees(comparison.budget)}</caption><thead><tr><th scope="col">Detail</th>{comparison.rows.map(r=><th scope="col" key={r.slot}>{comparison.offers.find(o=>o.slot===r.slot)?.shop}</th>)}</tr></thead><tbody>
      {[...Object.entries(labels),["total","Known total cost"],["fit","Fit against your needs"],["reason","Reasons"],["gaps","Needs checking"]].map(([k,label])=><tr key={k}><th scope="row">{label}</th>{comparison.rows.map(r=>{const o=comparison.offers.find(o=>o.slot===r.slot);let value=k==="gaps"?r.gaps.join(", ")||"No listed gaps":k==="total"?r.total===null?"Needs checking — incomplete costs":rupees(r.total):k==="fit"?r.fit:k==="reason"?r.reason:amounts.includes(k)?o.details[k]===null?"Not provided":rupees(o.details[k]):o.details[k];if(k==="validUntil"&&value==="Not provided")value="Validity not provided";return <td key={r.slot} className={comparison.stale?"":k==="fit"&&r.fit==="Fits your stated needs"?"fits":""}>{value}{k==="model"&&<p className="hint">Buyer-confirmed transcription · {time(o.confirmedAt)}<br/>Shopkeeper said; not verified</p>}{Object.hasOwn(labels,k)&&<Sources capture={data.captures.find(c=>c._id===o.captureId)}/>}</td>;})}</tr>)}
      </tbody></table></div>
    </section>}
  </section>;
}
