import React,{useEffect,useRef,useState} from "react";
import {useAction,useConvexAuth,useMutation,useQuery} from "convex/react";
import {api} from "../convex/_generated/api";
import {listenTurn} from "./voiceAudio";
const DRAFT="voice-offer-draft:v1",labels={model:"Exact model",price:"Quoted price",inclusions:"Included",extraCosts:"Extra costs",fit:"Fit / installation",warranty:"Warranty / service",validity:"Quote validity"},visible=["model","price","inclusions","extraCosts"];
const empty=()=>({requestId:[...crypto.getRandomValues(new Uint8Array(18))].map(n=>n.toString(16).padStart(2,"0")).join(""),language:"hi-IN",shop:"",brief:{item:"",budget:null,situation:""},turns:[],facts:[],corrections:[],reviewedKeys:[],consented:false,stage:"start"});
function read(){try{const d=JSON.parse(localStorage.getItem(DRAFT));if(d&&Array.isArray(d.turns)&&d.brief&&Array.isArray(d.facts)&&typeof d.requestId==="string")return {...d,stage:d.stage==="start"?"start":"review"};}catch{}return empty();}
async function digest(token){return [...new Uint8Array(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token)))].map(n=>n.toString(16).padStart(2,"0")).join("");}
export default function Voice({Account}) {
 const {isAuthenticated}=useConvexAuth(),setup=useQuery(api.voice.setup),savedResult=useQuery(api.voice.current),startSession=useMutation(api.voice.newSession),save=useMutation(api.voice.save),saveCorrection=useMutation(api.voice.correct),say=useAction(api.sarvam.say),turn=useAction(api.sarvam.turn);
 const saved=isAuthenticated?savedResult:null;
 const [draft,setDraft]=useState(read),[state,setState]=useState("Ready"),[error,setError]=useState(""),[signIn,setSignIn]=useState(false),[saving,setSaving]=useState(false),[correct,setCorrect]=useState(false),[playPending,setPlayPending]=useState(false),[deviceSaved,setDeviceSaved]=useState(true),[turnPending,setTurnPending]=useState(false);
 const wasAuthenticated=useRef(isAuthenticated);
 const data=useRef(draft),session=useRef(null),mic=useRef(null),sound=useRef(null),ctx=useRef(null),generation=useRef(0),active=useRef(false),mounted=useRef(true),pendingSound=useRef(null),saveBusy=useRef(false);
 function update(patch){const d={...data.current,...patch};data.current=d;setDraft(d);try{localStorage.setItem(DRAFT,JSON.stringify(d));setDeviceSaved(true);}catch{setDeviceSaved(false);}return d;}
 function stop(){generation.current++;active.current=false;mic.current?.cancel();mic.current=null;if(sound.current){sound.current.pause();sound.current.src="";sound.current=null;}pendingSound.current=null;setPlayPending(false);}
 useEffect(()=>{const offline=()=>{stop();setState("Connection lost — assistant stopped");setError("Your captured text remains here. Resume only when you choose.");};const hidden=()=>{if(document.hidden&&active.current){stop();setState("Paused — you have control");}};window.addEventListener("offline",offline);document.addEventListener("visibilitychange",hidden);return()=>{mounted.current=false;stop();ctx.current?.close();window.removeEventListener("offline",offline);document.removeEventListener("visibilitychange",hidden);};},[]);
 useEffect(()=>{if(isAuthenticated)setSignIn(false);if(wasAuthenticated.current&&!isAuthenticated){stop();session.current=null;setState("Paused — signed out, microphone off");}wasAuthenticated.current=isAuthenticated;},[isAuthenticated]);
 async function play(audio,after,version){if(!audio){setState("Paused — you have control");return;}const el=new Audio("data:audio/wav;base64,"+audio);sound.current=el;setState("Assistant speaking — microphone off");el.onended=()=>{el.src="";sound.current=null;if(version===generation.current)after?.();};el.onerror=()=>{stop();setError("Assistant speech could not play. Take over or resume.");setState("Paused — you have control");};try{await el.play();}catch{pendingSound.current={audio,after,version};setPlayPending(true);setState("Tap Play assistant to allow sound — microphone off");}}
 async function listen(version){if(version!==generation.current||!active.current)return;setState(data.current.stage==="brief"?"Listening to you — audio is not retained":"Listening in the shop — speaker needs checking");try{const handle=await listenTurn({context:ctx.current,onDone:audio=>processTurn(audio,version),onQuiet:()=>{active.current=false;setState("Paused — no clear speech heard");},onError:()=>{stop();setState("Paused — you have control");setError("The microphone stopped. Try permission again or take over.");}});if(version!==generation.current)handle.cancel();else mic.current=handle;}catch(e){stop();setState("Paused — you have control");setError(e.name==="NotAllowedError"?"Microphone access was refused. Allow it in your browser settings, then resume.":"Could not use your microphone. Close other recording apps and try again.");}}
 async function processTurn(audio,version){setTurnPending(true);mic.current=null;setState("Understanding the answer — microphone off");const d=data.current;try{
   const result=await turn({...session.current,audio,language:d.language,phase:d.stage==="brief"?"brief":"shop",turns:d.turns,brief:d.brief});audio="";if(!mounted.current||data.current.requestId!==d.requestId)return;
   let turns=d.turns;if(result.transcript)turns=[...turns,{speaker:d.stage==="brief"?"buyer":"shop",text:result.transcript,at:Date.now()}];
   const patch={turns,brief:result.brief,language:result.language};if(result.facts.length)patch.facts=[...d.facts.filter(f=>!result.facts.some(n=>n.key===f.key)),...result.facts];update(patch);
   if(version!==generation.current)return;
   if(result.error){stop();setError(result.error);setState("Paused — you have control");return;}
   if(result.code==="review"){stop();update({stage:d.stage==="brief"?"briefReview":"review"});setState("Ready to review — microphone off");return;}
   if(result.text)update({turns:[...data.current.turns,{speaker:"assistant",text:result.text,at:Date.now()}]});
   if(result.code==="handoff"){active.current=false;update({stage:"review"});await play(result.audio,()=>setState("Your decision — you have control"),version);return;}
   await play(result.audio,()=>listen(version),version);
 }catch(e){audio="";if(version!==generation.current)return;stop();setState("Paused — you have control");setError(typeof e.data==="string"?e.data:"Voice processing failed. The audio was discarded; earlier text remains. Repeat the last answer or take over.");}finally{if(mounted.current)setTurnPending(false);}}
 async function begin(code,nextStage){setError("");if(!setup?.ready){setError(setup?.message||"Checking voice setup. Try again shortly.");return;}if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia||!window.AudioContext){setError("Voice needs a secure HTTPS page and microphone support. This local Wi-Fi HTTP preview cannot capture voice on your phone.");return;}
  stop();const version=generation.current;active.current=true;setState("Starting voice — microphone off");try{ctx.current??=new AudioContext();await ctx.current.resume();if(!session.current){const token=[...crypto.getRandomValues(new Uint8Array(32))].map(n=>n.toString(16).padStart(2,"0")).join("");const sessionId=await startSession({tokenHash:await digest(token)});session.current={sessionId,token};}if(version!==generation.current)return;
  update({stage:nextStage});const result=await say({...session.current,code,language:data.current.language});if(version!==generation.current)return;update({turns:[...data.current.turns,{speaker:"assistant",text:result.text,at:Date.now()}]});await play(result.audio,code==="intro"?()=>{active.current=false;setState("Waiting for shopkeeper agreement — microphone off");}:()=>listen(version),version);
 }catch(e){if(version!==generation.current)return;stop();session.current=null;setState("Paused — you have control");setError(typeof e.data==="string"?e.data:"Could not start voice. Check setup or take over; no audio was retained.");}}
 async function resume(){setError("");if(data.current.stage!=="brief"&&!data.current.consented){setError("Introduce the assistant and confirm the shopkeeper agrees before capturing speech.");return;}if(!session.current){await begin(data.current.stage==="brief"?"brief":"unclear",data.current.stage==="brief"?"brief":"shop");return;}stop();const version=generation.current;active.current=true;try{ctx.current??=new AudioContext();await ctx.current.resume();await listen(version);}catch{stop();setError("Could not resume microphone. Try again.");}}
 function end(){stop();update({stage:data.current.turns.some(t=>t.speaker==="shop")?"review":"briefReview"});setState("Ready to review — microphone off");}
 async function saveOffer(confirm){if(saveBusy.current||turnPending)return;stop();const d=update({stage:"review",reviewedKeys:confirm?visible.filter(k=>data.current.facts.some(f=>f.key===k)):[]});if(!isAuthenticated){setSignIn(true);setState("Sign in to save — microphone off");return;}saveBusy.current=true;setSaving(true);setError("");try{await save({requestId:d.requestId,shop:d.shop,brief:d.brief,turns:d.turns,facts:d.facts,reviewedKeys:d.reviewedKeys,corrections:d.corrections});localStorage.removeItem(DRAFT);const cleared=empty();data.current=cleared;setDraft(cleared);setState("Saved");}catch(e){setError(typeof e.data==="string"?e.data:"Your offer isn't saved yet. Your draft remains here; retry saving.");}finally{saveBusy.current=false;setSaving(false);}}
 const shown=saved||draft,review=!!saved||draft.stage==="review",hasShop=draft.turns.some(t=>t.speaker==="shop"),isLive=state.startsWith("Listening")||state.startsWith("Assistant speaking")||state.startsWith("Understanding")||state.startsWith("Starting");
 return <section className="sheet voice-workspace" aria-labelledby="voice-title">
  <h1 id="voice-title">{saved?"Your first shop offer.":"Let your companion ask."}</h1>
  <p className="intro">{saved?"Reopened from your account. Conversation text is kept; audio is not.":"Tell it what you need. Let it ask the shopkeeper. Only you can accept a deal or promise to buy."}</p>
  {!saved&&setup&&!setup.ready&&<p className="voice-setup">{setup.message}</p>}
  {!saved&&draft.stage==="start"&&<>
   <label htmlFor="voice-language">Conversation language</label><select id="voice-language" value={draft.language} onChange={e=>update({language:e.target.value})}><option value="hi-IN">Hindi / Hinglish</option><option value="te-IN">Telugu / Telugu mixed with English</option></select>
   <p>Speak naturally, including English product names. Mixed-language accuracy still needs testing.</p>
   <p className="hint">Sarvam processes each spoken turn. This app retains text only. Audio is discarded after processing. Tell both participants before starting.</p>
   <button className="primary" disabled={setup===undefined} onClick={()=>begin("brief","brief")}>Tell me what you’re buying</button><p className="hint">Calling isn't available yet.</p>
  </>}
  {!saved&&draft.stage!=="start"&&<p className="voice-state" role="status">{state}</p>}
  {(shown.brief.item||draft.stage==="briefReview"||saved)&&<details className="voice-brief" open={draft.stage==="briefReview"&&!saved}><summary>Your needs — only for you</summary><p>{shown.brief.item||"Product needs checking"}</p><p>Budget: {shown.brief.budget===null?"Needs checking":new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(shown.brief.budget)}</p>{shown.brief.situation&&<p>{shown.brief.situation}</p>}</details>}
  {!saved&&draft.stage==="briefReview"&&<><p>Check this short brief before the shop conversation.</p><button className="secondary" onClick={()=>begin("brief","brief")}>Correct my needs by speaking</button>{draft.brief.item&&<>
   <label htmlFor="voice-shop">Shop name or a name you’ll recognise</label><input id="voice-shop" maxLength={120} value={draft.shop} onChange={e=>update({shop:e.target.value})}/>
   <p>Ask the shopkeeper if an AI assistant can talk with them and save the conversation text. No audio recording is kept by this app.</p>
   <button className="primary" disabled={!draft.shop.trim()} onClick={()=>begin("intro","consent")}>Looks right — introduce the assistant</button></>}
  </>}
  {!saved&&draft.stage==="consent"&&<div className="actions"><button className="primary" onClick={()=>{update({stage:"shop",consented:true});begin("model","shop");}}>Shopkeeper agrees — start enquiry</button><button className="secondary" onClick={()=>{stop();update({stage:"briefReview",consented:false});setState("Shopkeeper declined — microphone off");}}>Shopkeeper declines</button></div>}
  {review&&<><h2>{shown.shop||"Offer summary"}</h2><p className="hint">Shopkeeper said; not verified. A quoted price is not a full total when extra costs are unknown.</p><dl className="voice-facts">{visible.map(k=>{const fact=shown.facts.find(f=>f.key===k),correction=shown.corrections.find(c=>c.key===k);return <div key={k}><dt>{labels[k]}</dt><dd>{k==="price"&&/^\d+(\.\d{1,2})?$/.test(correction?.value||fact?.value||"")?new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(correction?.value||fact?.value)):(correction?.value||fact?.value||"Not provided")}{saved&&shown.reviewedKeys.includes(k)&&<span className="hint">Buyer-confirmed transcription</span>}{correction&&<span className="hint">Buyer correction; original conversation kept</span>}</dd></div>;})}</dl>
   {saved?<><p className="footnote">Saved · Last saved {new Date(saved.updatedAt).toLocaleString("en-IN")}</p><button className="secondary" onClick={()=>setCorrect(!correct)}>Correct a saved detail</button></>:<><p>Looks right confirms only these displayed facts. Other captured details remain unreviewed.</p>{turnPending&&<p role="status">Finishing the captured turn before saving. The assistant stays paused if you paused it.</p>}{hasShop?<div className="actions"><button className="primary" disabled={saving||turnPending} onClick={()=>saveOffer(true)}>{saving?"Saving…":"Looks right — save offer"}</button><button className="secondary" disabled={saving} onClick={()=>setCorrect(!correct)}>Correct something</button><button className="secondary" disabled={saving||turnPending} onClick={()=>saveOffer(false)}>I don’t know — save unreviewed</button></div>:<p>No shop response was captured. Resume the enquiry before saving an offer.</p>}

   {signIn&&<div className="voice-signin"><Account/><button className="secondary" onClick={()=>setSignIn(false)}>Back to offer</button></div>}
   </>}
   {correct&&<form className="voice-correction" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget),key=String(f.get("key")),value=String(f.get("value")).trim();if(saved){setSaving(true);setError("");try{await saveCorrection({offerId:saved._id,key,value});setCorrect(false);}catch(err){setError(typeof err.data==="string"?err.data:"Your correction was not saved. Keep it here and retry.");}finally{setSaving(false);}}else{update({corrections:[...draft.corrections.filter(c=>c.key!==key),{key,value}],reviewedKeys:[]});setCorrect(false);}}}><label htmlFor="correct-key">Which detail?</label><select id="correct-key" name="key">{visible.map(k=><option key={k} value={k}>{labels[k]}</option>)}</select><label htmlFor="correct-value">Your correction</label><input id="correct-value" name="value" maxLength={1000} required/><button className="secondary" disabled={saving}>{saving?"Saving…":saved?"Save correction":"Keep correction"}</button></form>}
   {shown.facts.some(f=>!visible.includes(f.key))&&<details><summary>Other captured details — unreviewed</summary>{shown.facts.filter(f=>!visible.includes(f.key)).map(f=><p key={f.key}><strong>{labels[f.key]}:</strong> {f.value}</p>)}</details>}
  </>}
  {shown.turns.length>0&&<details><summary>Read conversation text ({shown.turns.length} turns)</summary><p className="hint">Shop-side speech may include other speakers. Speaker identity is not verified. Original text is kept when you correct a summary.</p><ol className="voice-transcript">{shown.turns.map((t,i)=><li key={i}><strong>{t.speaker==="assistant"?"Assistant":t.speaker==="buyer"?"Buyer brief":"Shop-side speech — speaker needs checking"}</strong><p>{t.text}</p></li>)}</ol></details>}
  {error&&<p className="error" role="alert">{error}</p>}
  {!saved&&draft.stage!=="start"&&<div className="voice-controls"><button className="secondary" onClick={()=>{stop();setState("Paused — you have control");}}>Pause</button><button className="secondary" onClick={()=>{stop();setState("You have control — microphone off");}}>Take over</button>{isLive&&state.startsWith("Listening")&&<button className="secondary" onClick={()=>mic.current?.finish()}>Answer finished</button>}<button className="secondary" disabled={saving} onClick={end}>End conversation</button>{!isLive&&(draft.stage==="brief"||draft.consented)&&<button className="primary" disabled={saving} onClick={resume}>Resume assistant</button>}{playPending&&<button className="primary" onClick={()=>{const p=pendingSound.current;pendingSound.current=null;setPlayPending(false);if(p)play(p.audio,p.after,p.version);}}>Play assistant</button>}</div>}
  {!saved&&<p className="footnote">{saving?"Saving…":deviceSaved?"Draft on this device; not saved to your account. Text only. Closing during an unheard or unfinished turn may require repeating it.":"Device draft could not be saved. Keep this page open until your offer is saved."}</p>}
  {!saved&&!signIn&&!isAuthenticated&&<button className="text-button" onClick={()=>{stop();setSignIn(true);}}>Sign in to reopen my offer</button>}
  {!saved&&signIn&&draft.stage!=="review"&&<div className="voice-signin"><Account/><button className="secondary" onClick={()=>setSignIn(false)}>Back to conversation</button></div>}
  <p><a href="/app.html?legacy=1">Reopen earlier notes, photos and comparisons</a></p>
 </section>;
}
